import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

const blog = defineCollection({
  // Files starting with "_" are ignored, handy for notes and unfinished ideas.
  loader: glob({ base: './src/content/blog', pattern: '**/[^_]*.{md,mdx}' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    pubDate: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    topic: z.string(),
    /** Drafts render in `astro dev` only. */
    draft: z.boolean().default(false),
    /** Set on files generated by `npm run sync:notion`; the script owns (and may delete) them. */
    notionId: z.string().optional(),
  }),
});

/** Case studies. Facts (url, dates, highlights) come from the matching cv.json `projects` entry. */
const projects = defineCollection({
  loader: glob({ base: './src/content/projects', pattern: '**/[^_]*.{md,mdx}' }),
  schema: z.object({
    /** Must equal the `name` of an entry in cv.json `projects`. */
    project: z.string(),
    /** Meta description, ~155 characters. */
    description: z.string(),
    updatedDate: z.coerce.date().optional(),
    /** Drafts render in `astro dev` only. */
    draft: z.boolean().default(false),
  }),
});

export const collections = { blog, projects };
